class Solution {

    // Solution @ Sergey Leschev

    // 389. Find the Difference
    // You are given two strings s and t.
    // String t is generated by random shuffling string s and then add one more letter at a random position.
    // Return the letter that was added to t.

    // Finds the letter that appears just in t.
    // - Parameters:
    //   - s: The string.
    //   - t: The string.
    // - Returns: The letter that appears just in t.

    // Example 1:
    // Input: s = "abcd", t = "abcde"
    // Output: "e"
    // Explanation: 'e' is the letter that was added.

    // Example 2:
    // Input: s = "", t = "y"
    // Output: "y"

    // Example 3:
    // Input: s = "a", t = "aa"
    // Output: "a"

    // Example 4:
    // Input: s = "ae", t = "aea"
    // Output: "a"

    // Constraints:
    // 0 <= s.length <= 1000
    // t.length == s.length + 1
    // s and t consist of lower-case English letters.

    // - Complexity:
    //   - time: O(n), where n is the length of t.
    //   - space: O(1), only constant space is used. The total number of unique characters is 26.
    
    func findTheDifference(_ s: String, _ t: String) -> Character {
        var dict = [Character: Int]()
        for ch in s { dict[ch, default: 0] += 1 }

        for ch in t {
            guard let num = dict[ch], num > 0 else { return ch }
            dict[ch] = num - 1
        }

        return "\0"
    }

}